### PR TITLE
Add responsive image crop, styles for 28:9

### PR DESCRIPTION
**Pull request by finnlewis**
This is a collection of image styles and responsive image preset, with crop, to support a 28:9 ratio image used on subsite banners.

### CODE REVIEW

**Review by Adnan-cds — COMMENTED** [review]
There are **four** files here that belong to the various banner related paragraphs.  These belong to the localgov_subsites module at the moment e.g. [core.entity_form_display.paragraph.localgov_banner_primary.default.yml](https://github.com/localgovdrupal/localgov_subsites/blob/master/config/install).  If you please have a look @finnlewis

**Comment by finnlewis** [comment]
Thanks @Adnan-cds - good spot, sorry. I've removed those files and have re-triggered the tests.

**Comment by Adnan-cds** [comment]
Thanks Finn.  Files look good.  I will test it all in an empty site and get back to you.

**Comment by Adnan-cds** [comment]
## Results from quick test
Hi Finn,
I installed this branch on a fresh install of LocalGov.  Here' what happened:
- The "Responsive banner" checkbox is not select within the "Custom display settings" section in /admin/structure/media/manage/image/display.  This means the "Responsive banner" view mode is not available for Media images by default.
- I configured the "Image" field of the "Image" paragraph to use the "Responsive banner" *view mode* from /admin/structure/paragraphs_type/localgov_image/display
- Uploaded a Media image and applied the 28:9 crop.
- Added an Image Page component in a Service page and selected the above mentioned Media image.
- When I view this Service page, the Image is using the "Large 3:2 2x" image style rather than 28:9.  Sample image path: /sites/default/files/styles/large_3_2_2x/public/2020-12/SPHERE_image_of_the_disc_around_AB_Aurigae.jpg?itok=UXfAeG2-
- Eventually, I manually enabled the "Responsive banner" view mode for the Media image display from /admin/structure/media/manage/image/display
- When I looked at the config for the "Responsive banner" view mode from /admin/structure/media/manage/image/display/responsive_banner, I could see that the Image field is using the "Image 3:2" Responsive image style rather than "Banner (28:9)" Responsive image style.  Once I selected "Banner (28:9)", all was good.
- I looked at core.entity_view_display.media.image.responsive_banner.yml as that defines the "Responsive banner" view mode and that looks okay.  So I am not sure why this is happening.

Please see if you can reproduce this.

FAO @finnlewis

**Comment by finnlewis** [comment]
Thanks @Adnan-cds  - that all rings a bell - I'm not sure why this happens.
I will test.

**Comment by finnlewis** [comment]
I ran through the same thing @Adnan-cds and then enable the view mode on the media image, then exported the config again and added it back. It seems to have removed a dependency on field_formatter_class which, as it is in optional, maybe just prevented the config from installing.

A fresh install now does have the 'responsive banner' view mode enabled and configured: 
image

**Comment by finnlewis** [comment]
Further to this, enabling the localgov_subsites module on the feature/7-default-display-banner-navigation branch uses the responsive banner view mode and the 28:9 crop.

**Comment by Adnan-cds** [comment]
> It seems to have removed a dependency on field_formatter_class which

Ah... we use this field_formatter_class module too.  Very useful.  I wish it were part of the distribution (along with [block_class](https://www.drupal.org/project/block_class)).  Saves a lot of custom templating.

Anyway, just tested this change again and all works fine now :D

**Review by Adnan-cds — APPROVED** [review]
Thanks a lot :)

**Pull request merged**
