### PR TITLE
Forward port of paragraphs field rename bugfix to 2.x

### PR DESCRIPTION
**Pull request by andybroomfield**
Port the fix in #76 to 2.x branch

- Update paragraph tables with references to new field names
- Coding standards fixes
- Add test for paragraph fix on field rename
- Coding standards fix and rename the test
- Fix test to call the entity reference revisions purger
- Add extra if to fieldrenamehelper to detect entity_referenece_revisions
- Throw exception if renaming a non paragraph entity_reference_revisions

### CODE REVIEW

**Comment by andybroomfield** [comment]
If tests on this pass, I'll let @stephen-cox review just to make sure its done correctly.

**Comment by andybroomfield** [comment]
Looks like we need #80 added before this.

**Comment by stephen-cox** [comment]
#80 has been merged, so merging 2.x into this should fix the test run

**Review by stephen-cox — APPROVED** [review]
Looks good

**Pull request merged**
