### PR TITLE
Drupal 10 support

### PR DESCRIPTION
**Pull request by stephen-cox**
This adds Drupal 10 support. The two major changes that come with this are:

## Now installs CKEditor 5 

CKEditor 4 is currently deprecated and removed in D10. We probably want to check the config for this. Do we perhaps want to move to CKEditor 5 now?

## ~~Media config is now in `install` rather than `optional`~~

~~This hasn't caused any further issues with installing other modules, but should be tested with current install and Microsites as well.~~

### CODE REVIEW

**Comment by finnlewis** [comment]
Very cool @stephen-cox !

**Comment by andybroomfield** [comment]
> CKEditor 4 is currently deprecated and removed in D10. We probably want to check the config for this. Do we perhaps want to move to CKEditor 5 now?

What are the potentional issues here? Assume this would install for anyone on new sites, others would still need to upgrade? Is this something that would justify a 3.x branch of core?

**Comment by andybroomfield** [comment]
Also did #158 and the followup get resolved, ie. moving the media into install. Assume it did based on
> This hasn't caused any further issues with installing other modules, but should be tested with current install and Microsites as well.

but be good to confirm.

**Comment by finnlewis** [comment]
Discussed in Merge Monday, continue to test and review this week, not ready for merge yet.

- [ ] test in microsites profile

Putting into draft

**Comment by stephen-cox** [comment]
I have found a  potential issue with moving config in LocalGov Media to install.

Much of this config also exists in the Standard Drupal profile that comes with core. If you try to enable LocalGov Media when using the Standard profile it will fail with an error about config already existing.

Is there a use case for installing LocaGov modules in a site using the Standard profile? If so we're going to have to think of a way around this. For example, keep config in optional and add a hook that installs the config if using the localgov profile.

**Comment by andybroomfield** [comment]
@stephen-cox yes, I don't think we should assume the profile is how everyone installs modules, the goal was that modules can be installed independantly which really could mean installing them in a otherwise standard profile site (I've also been testing modules this way).

Also I thought the arguments around requiring or installing modules in the profile was that profile would set up how the site is intended to use, but those who didn't want could install modules independantly.

As a workaround, could the already in standard media config be moved to optional? or some module use a config/override directory and place config in there?

**Comment by ekes** [comment]
I for one have chatted to people about installing: Directories, Step-By-Step, and Alert Banner outside of the profile. I'd expect Subsites might be another.

**Comment by ekes** [comment]
Is the sticking point on this one the media config location?

**Review by ekes — APPROVED** [review]
New installs will get ckeditor 5 works fine. It is available for switching for existing installs.
Tested against an existing d9 localgov test db and nothing adverse. Permissions and ckeditor5 on a new install look good. Tests pass.

Is there some way of tracking where the permissions are getting installed and doing that step-wise? Even maybe not removing them all from here yet till the others are committed?

**Comment by finnlewis** [comment]
Discussing in Merge Monday with Ekes.

Currently we have lots of merge requests for Drupal 10, some approved, but planning to not merge these yet and discuss to review how to get the D10 branches working without breaking the D9 installs.

Suggesting that we either need to:
 - focus on the D9 branches, keeping them working while making releases that start to support D10
 - co-ordinate merge and release across all projects.

Note: we have a Technical Governance meeting on Wednesday where we will focus on confirming the strategy for this.

Ekes suggested listing all modules: 
 - projects that will support D9 and D10
 - projects that will need different branches. 

See https://github.com/localgovdrupal/localgov/issues/480

**Pull request merged**
