### PR TITLE
Add a freestyle crop, image styles and responsive image style, image…

### PR DESCRIPTION
**Pull request by msayoung**
… view mode

### CODE REVIEW

**Review by finnlewis — APPROVED** [review]
Tested locally and works for me on a fresh install with localgov_demo enabled. 

This will only affect fresh installs too. 

Thanks @msayoung !

**Review by markconroy — COMMENTED** [review]
Checked on microsites and this does what it says on the tin, however I'm wary of the responsive freestyle image style. Just because someone is on a large screen does not mean they will want each freestyle image to be 1200px wide. For example, embedding a headshot of a councillor. you might just want it to be 300px wide.

Is this a concern? If not, I'm happy to approve.

**Comment by msayoung** [comment]
It's true - Do you have any thoughts on how we deal with this @markconroy ?

**Comment by finnlewis** [comment]
From our discussion on the Merge Monday call, I think we're good to go with this @msayoung 

We noted we would follow up on another issue with @markconroy to explore how to give content designers the info they need.

**Pull request merged**
