### PR TITLE
Add media_library_edit to allow media items to be edited after they'v…

### PR DESCRIPTION
**Pull request by msayoung**
…e been uploaded

### CODE REVIEW

**Comment by andybroomfield** [comment]
Question, should this be added to the profile instead of core?
As its adding something as a standard experince, but there is nothing in localgov_core that would depend on it?
Although I think the other content types will need to be updated to use media_library_edit as the field widget.

Otherwise its a good call, we use it at BHCC as its odd it doesn't do this be default.

**Comment by msayoung** [comment]
Hi @andybroomfield 
There is an issue to get the functionality in to Drupal core, and a patch that we could use. https://www.drupal.org/project/drupal/issues/2985168 
It's been delayed though, pending input from the UX and a11y teams. 

I put this in localgov_core as the localgov_media submodule lives here. But happy to move it if that's better. 

There's another PR for adding this to localgov_paragraphs - and if these two go in, I'll update localgov_news and localgov_events also. I _think_ this should cover it, but there may be more.

**Comment by finnlewis** [comment]
I think we should add it here. The fact that we have submodules means we need to add dependencies for those submodules to our project composer.json. Either that or split out the submodules. So far we've been opting for the former.

**Review by finnlewis — APPROVED** [review]
I'm happy with this! Thanks @msayoung and @andybroomfield ! :)

**Review by andybroomfield — APPROVED** [review]
As per merge Monday, as used by other modules.

To consider in future if localgov_media should be own module.

**Pull request merged**
