### PR TITLE
Documentation for 459b0f0 fixes #30.

### LINKED ISSUE #30: Installing permissions for authors and content editors
The localgov_roles module installs permissions for the 4 service content types. It doesn't do anything for other content types as we don't know which other content types will be enabled at install time. We need some way of installing these so athours and editors can use the workflow defined in localgov_workflow.

### PR DESCRIPTION
**Pull request by ekes**
README with module explanation, and documentation of the new hook to set default permissions.

### CODE REVIEW

**Comment by finnlewis** [comment]
I've just been testing this locally, and found schema changes in office_hours module. 

I've created this issue https://github.com/localgovdrupal/localgov_paragraphs/issues/32

And: https://github.com/localgovdrupal/localgov_paragraphs/pull/33/files

**Review by andybroomfield — APPROVED** [review]
Not sure what is meant by the title, however I think this is fine to add the documentation around permissions.
(I assume this is for localgov_roles only)

**Comment by ekes** [comment]
The title refers to https://github.com/localgovdrupal/localgov_core/commit/459b0f0d9eaa21d680907ff8fc5a0f5bde3f9968 which added the HOOK_localgov_roles_default to install default permissions for modules (requested in #30) and is the primary reason I wrote the README so that people would know how to implement the hook.

**Comment by finnlewis** [comment]
@ekes @stephen-cox any idea why the tests are still failing here, but passing locally? 

Does the test runner cache old builds at all?

**Pull request merged**
