### PR TITLE
Workflow approvals dashboard

### LINKED ISSUE #95: Workflow: approval dashboard
## User story 

**As an** editor,
**I want to:** view a list of content sent for approval,
**So that** I can review/approve/reject as necessary

## Notes

An approvals dashboard is a view in Drupal that can be accessed by editors. 
Suggest this is a tab available from the Content Overview screen.

It must show a list of content that has been sent for approval and yet to be approved/published.

By default, it should be sorted to show content that was sent for approval first (last updated?) . There should also be an option to sort showing content that was most recently sent for approval.

## Acceptance tests:

1. Log in as and editor
2. Navigate to the moderated queue
3. Columns include:
·       Title (clickable to page front end/preview)
·       Content type
·       Author
·       Sent for approval date and time
·       Status – this should always be ‘sent for approval’
·       Approve/reject/edit (clickable to page back end/edit screen)
4. When an editor approves or rejects a page edit, the content should no longer appear in the dashboard.
5. Log in as author
6. See the moderation queue
7. Not be able to do anything 

## Wireframe: 

https://design.penpot.app/#/view/e136cb40-d014-11eb-97a9-7472ffaca84b/e136cb41-d014-11eb-97a9-7472ffaca84b?token=mKLdKAWLPeTj3zF8Bk-A0A&index=0 

## Suggested tasks:

- [x] Take a quick look at https://www.drupal.org/project/workbench to see
- [x] Demo https://www.drupal.org/project/workbench to the working group if it seems like a goer. 
- [x] Build out changes either on top of workbench or with core views

### PR DESCRIPTION
**Pull request by stephen-cox**
Adds approvals dashboard view and hides link to content moderation view when only the LocalGov workflow is enabled.

Closes #95

### CODE REVIEW

**Comment by stephen-cox** [comment]
Functionality for this work has been tested on #95 so this just needs a code review.

**Review by finnlewis — APPROVED** [review]
This works for me. 
@Adnan-cds / @andybroomfield if either of you have time to cast your eyes over this too, that would be great.

**Comment by finnlewis** [comment]
@andybroomfield did you get a chance to check in on this one too?

**Review by andybroomfield — APPROVED** [review]
Ok, this is fine for now.

**Pull request merged**
