### PR TITLE
Changes generator tag to say LocalGov Drupal.

### PR DESCRIPTION
**Pull request by rupertj**
Implements #176.

### CODE REVIEW

**Comment by finnlewis** [comment]
Interesting, I like it! 

Any thoughts @ekes @stephen-cox @andybroomfield @Adnan-cds ?

**Comment by andybroomfield** [comment]
What is the reason to use a code to do this, can it not be done in metatag module?

**Comment by rupertj** [comment]
I didn't think of using metatag to do it, TBH.

But I've just tried it and it'll only add a second one, not replace the existing one:
Screenshot 2023-06-05 at 14 14 33

"Hello" is the one I put in with metatag.

**Comment by finnlewis** [comment]
@stephen-cox suggests that this might better live in the localgov profile rather than in localgov_core, which could be installed in a separate site.

**Comment by ekes** [comment]
Notice thunder does it in the profile and then it is in _attachments rather than attachments_alter is that cleaner? https://git.drupalcode.org/project/thunder/-/blob/6.5.x/thunder.profile#L132

**Comment by finnlewis** [comment]
Sounds like moving it to the profile is probably best.

Also discussing with @markconroy  and @stephen-cox - it would be good to keep the 'Drupal 9...' prefix like Thunder do: 

https://git.drupalcode.org/project/thunder/-/blob/6.5.x/thunder.profile#L140

So maybe: 

'Drupal 9 - LocalGov Drupal (https://localgovdrupal.org)';

**Comment by finnlewis** [comment]
Note from Merge Monday: this should be in the profile, not in localgov_core. 

@rupertj fancy moving this to the profile?

**Review by stephen-cox — CHANGES_REQUESTED** [review]
As mentioned by @finnlewis - it's possible for someone to install some of the LocalGov modules separately and localgov_core would likely be installed as a dependency, so I think this should be move to the profile.

**Comment by finnlewis** [comment]
Checking in at Merge Monday - @rupertj you able to take a look at this? 

If not, @alexburrows might be able to 🛩️

**Comment by rupertj** [comment]
I've been meaning to come back and pick this up and move it to the profile as suggested, but haven't had a chance to yet. If @alexburrows (or anyone else) would like to, they'd be very welcome to.

**Comment by alexburrows** [comment]
I'll take this on, it should really go into the localgov profile itself. So I will create a new PR in the profile repo.

**Comment by andybroomfield** [comment]
Closing as we merged the version of this into the localgov profile.
https://github.com/localgovdrupal/localgov/pull/601

**Pull request closed without merging**
